"""
Shared type definitions for the LLM-based WorldModel formation pipeline.

These data classes represent the intermediate artifacts produced by each
stage of the pipeline: agent specifications, multi-agent domain/task specs,
concurrent effect rules, and incremental update types.
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

# Re-export L2P types that we use alongside our own
from l2p.utils.pddl_types import Action, Function, Predicate


@dataclass
class AgentSpec:
    """Specification of an agent extracted from natural language."""

    name: str  # e.g. "robot", "human"
    agent_type: str  # e.g. "robot", "person"
    capabilities: List[str]  # NL descriptions of what the agent can do
    action_hints: List[str]  # Candidate action names (NL)


@dataclass
class ConcurrentEffect:
    """Describes how two simultaneous actions interact."""

    agent_a: str  # Name of first agent
    action_a: str  # Action name of first agent
    agent_b: str  # Name of second agent
    action_b: str  # Action name of second agent
    effect_type: str  # "commutative" | "conflicting" | "synergistic"
    resolution: str  # NL description of what happens
    pddl_condition: Optional[str] = None  # PDDL condition for when conflict occurs
    pddl_effect: Optional[str] = None  # PDDL effect override (if non-commutative)


@dataclass
class MADomainSpec:
    """Multi-agent PDDL domain specification (no goals)."""

    name: str
    types: Dict[str, str] = field(default_factory=dict)
    constants: Dict[str, str] = field(default_factory=dict)
    predicates: List[Predicate] = field(default_factory=list)
    functions: List[Function] = field(default_factory=list)
    agents: List[AgentSpec] = field(default_factory=list)
    agent_actions: Dict[str, List[Action]] = field(
        default_factory=dict
    )  # agent_name → actions
    concurrent_effects: List[ConcurrentEffect] = field(default_factory=list)
    requirements: List[str] = field(default_factory=list)


@dataclass
class MATaskSpec:
    """Multi-agent PDDL task specification (no goals)."""

    name: str
    domain_name: str
    objects: Dict[str, str] = field(default_factory=dict)
    initial_state: List[str] = field(default_factory=list)
    agent_objects: Dict[str, List[str]] = field(
        default_factory=dict
    )  # agent_name → owned objects


@dataclass
class PrescribedAction:
    """An action option provided by the environment, not generated by the LLM."""

    name: str  # Human-readable action label
    description: str  # NL description (e.g. the choice text)
    agent: str  # Which agent this action belongs to
    pddl_action: Optional[Action] = None  # Formalized PDDL action schema (set by LLM)
    predicted_effects_nl: Optional[str] = (
        None  # NL prediction of what happens (set by LLM)
    )


@dataclass
class StateObservation:
    """An observed state from the environment, used for incremental updates."""

    description: str  # NL description of the new state/scene
    prescribed_actions: List[PrescribedAction] = field(
        default_factory=list
    )  # Actions available
    source_state: Optional[Any] = None  # The state from which we arrived
    source_action: Optional[int] = None  # The action index that led here
    metadata: Dict[str, Any] = field(
        default_factory=dict
    )  # Arbitrary env-specific metadata
